kind: pipeline
type: kubernetes
name: MINHA PIPE 


######################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request   


###################################################   build-push
steps:
- name: build-push
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run  
  privileged: true
  commands:
  - sleep 5 ## give docker enough time to start
  - docker login -u ${DOCKER_HUB_USERNAME}  -p ${DOCKER_HUB_PASSWORD}  #ou qualquer registry
  - docker build  -t {{ .repo.name }}:${DRONE_COMMIT_SHA:0:7} -f ./.nixpacks/Dockerfile .
  - docker push {{ .repo.name }}:${DRONE_COMMIT_SHA:0:7}

######################################################   Delivery
- name: delivery
  image: kub3dev/drone-deploy-version:1.0
  commands:
  - git clone git@github.com:kub3dev/devops.git
  - cd deploy-applications 
  - sed -E -i.bak 's%({{ .repo.name }}:).*%{{ .repo.name }}:${DRONE_COMMIT_SHA:0:7}%' apps/production/devops-app/deployment.yaml
  - git add . && git commit -m "Change image site-poc to {{ .repo.name }}:${DRONE_COMMIT_SHA:0:7}" && git push


########################################################   Services   
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
volumes:
- name: dockersock
  temp: {}