kind: pipeline
type: kubernetes
name: Production Pipeline 


######################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request   


###################################################   build-push
steps:
- name: build-push
  image: docker:dind
  environment:
    DOCKER_HUB_USERNAME: 
      from_secret: DOCKER_HUB_USERNAME
    DOCKER_HUB_PASSWORD: 
      from_secret: DOCKER_HUB_PASSWORD
  volumes:
  - name: dockersock
    path: /var/run  
  privileged: true
  commands:
  - sleep 5 ## give docker enough time to start
  - docker login -u $DOCKER_HUB_USERNAME  -p $DOCKER_HUB_PASSWORD #ou qualquer registry
  - docker build -t $DRONE_REPO:$DRONE_BUILD_NUMBER -t $DRONE_REPO:latest -f ./.nixpacks/Dockerfile .
  - docker push --all-tags $DRONE_REPO

- name: git-push
  image: appleboy/drone-git-push
  settings:
    branch: main
    remote: git@github.com:kub3dev/devops.git
    force: false
    commit: true
    commit_message: "Deploying version $DRONE_BUILD_NUMBER"
    commands:
    - cd apps/production/$DRONE_REPO_NAME
    - sed -E -i.bak 's%($DRONE_REPO:).*%$DRONE_REPO:$DRONE_BUILD_NUMBER%' deployment.yaml

######################################################   Delivery
- name: delivery
  image: kub3dev/drone-deploy-version:1.0
  commands:
  - git clone git@github.com:kub3dev/devops.git
  - cd apps/production/$DRONE_REPO_NAME
  - sed -E -i.bak 's%($DRONE_REPO:).*%$DRONE_REPO:$DRONE_BUILD_NUMBER%' deployment.yaml
  - git add . && git commit -m "Change image site-poc to $DRONE_REPO:$DRONE_BUILD_NUMBER" && git push

########################################################   Services   
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
volumes:
- name: dockersock
  temp: {}
  